ami                 = "ami-07efac79022b86107"
key_name            = "media_wiki"
public_key_path     = "/home/ubuntu/.ssh/media_wiki.pub"
web_instance_type   = "t2.micro"
db_instance_type    = "t2.micro"
aws_profile         = "mediawiki"